iname: Run Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave selenium allure-behave flask

    - name: Start Flask app
      run: |
        nohup python app.py &
        sleep 5

    - name: Run Behave tests
      run: behave -f allure_behave.formatter:AllureFormatter -o allure-results

    - name: Generate Allure report
      run: |
        pip install allure-pytest
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
     - name: Deploy Allure report to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: allure-report

     - name: Notify Slack
       uses: rtCamp/action-slack-notify@v2
       env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_MESSAGE: "✅ Behave tests passed for commit ${{ github.sha }}"

